service: appsync-todolist

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  postConfirmation:
    handler: functions/postConfirmation/handler.postConfirmation
    memorySize: 128
    timeout: 29

appSync:
  name: todos-api

  logging:
    level: ALL

  xrayEnabled: false

  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !Ref CognitoUserPool
      defaultAction: ALLOW

  dataSources:
    todos:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref Todos

  resolvers:
    - Query.getTodo:
        kind: UNIT
        dataSource: todos
        code: mapping-templates/Query.getTodo.js
    - Mutation.createTodo:
        kind: UNIT
        dataSource: todos
        code: mapping-templates/createTodo.js


resources:
  Resources:
    Todos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      DependsOn: PostConfirmationLambdaFunction
      Properties:
        UserPoolName: ${self:service}-cognito-pool-${self:custom.stage}
        AutoVerifiedAttributes:
          - email
        LambdaConfig:
          PostConfirmation:
            Fn::GetAtt:
              - PostConfirmationLambdaFunction
              - Arn
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
        Schema:
          - Name: email
            Required: true
            Mutable: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-client-${self:custom.stage}
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH

  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
